/**
 * AUTO-GENERATED by extract_mnfsr.py
 * Source: MNFSR Crops Area and Production District Wise 2024-25
 * Generated: 2026-05-16 14:15
 *
 * This replaces the fake generateProductionData() random number generator
 * with REAL government data from the Ministry of National Food Security & Research.
 *
 * HOW TO USE:
 * 1. Copy this file to your Backend/seeds/ directory
 * 2. Replace your 04-surplusDeficit.seed.js with this file
 * 3. Run: node seeds/04-surplusDeficit.seed.js
 */

const mongoose = require('mongoose');
const ProductionData = require('../models/ProductionData');
const SurplusDeficit = require('../models/SurplusDeficit');
const District = require('../models/District');
const CropType = require('../models/CropType');

// REAL district-level production data from MNFSR 2024-25
// Units: area in hectares, production in tonnes, yield in tonnes/hectare
const REAL_DISTRICT_DATA = 
{
  "PB-BWN": {
    "WHEAT": {
      "area_ha": 435000.0,
      "production_t": 1557000.0,
      "yield_t_per_ha": 3.5793
    },
    "RICE": {
      "area_ha": 152970.0,
      "production_t": 358030.0,
      "yield_t_per_ha": 2.3405
    },
    "COTTON": {
      "area_ha": 272750.0,
      "production_t": 142174.4,
      "yield_t_per_ha": 0.5213
    }
  },
  "PB-RYK": {
    "WHEAT": {
      "area_ha": 331000.0,
      "production_t": 1211000.0,
      "yield_t_per_ha": 3.6586
    },
    "RICE": {
      "area_ha": 75680.0,
      "production_t": 138790.0,
      "yield_t_per_ha": 1.8339
    },
    "COTTON": {
      "area_ha": 195050.0,
      "production_t": 78116.7,
      "yield_t_per_ha": 0.4005
    }
  },
  "PB-BWP": {
    "WHEAT": {
      "area_ha": 304000.0,
      "production_t": 1101000.0,
      "yield_t_per_ha": 3.6217
    },
    "RICE": {
      "area_ha": 27910.0,
      "production_t": 53210.0,
      "yield_t_per_ha": 1.9065
    },
    "COTTON": {
      "area_ha": 234310.0,
      "production_t": 119593.3,
      "yield_t_per_ha": 0.5104
    }
  },
  "PB-JHG": {
    "WHEAT": {
      "area_ha": 269000.0,
      "production_t": 1015000.0,
      "yield_t_per_ha": 3.7732
    },
    "RICE": {
      "area_ha": 192230.0,
      "production_t": 418090.0,
      "yield_t_per_ha": 2.1749
    },
    "COTTON": {
      "area_ha": 14570.0,
      "production_t": 8154.9,
      "yield_t_per_ha": 0.5597
    }
  },
  "PB-FSD": {
    "WHEAT": {
      "area_ha": 248000.0,
      "production_t": 939000.0,
      "yield_t_per_ha": 3.7863
    },
    "RICE": {
      "area_ha": 44400.0,
      "production_t": 308900.0,
      "yield_t_per_ha": 6.9572
    },
    "COTTON": {
      "area_ha": 11330.0,
      "production_t": 7990.0,
      "yield_t_per_ha": 0.7052
    }
  },
  "PB-ATK": {
    "WHEAT": {
      "area_ha": 181000.0,
      "production_t": 262000.0,
      "yield_t_per_ha": 1.4475
    },
    "RICE": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "PB-RWP": {
    "WHEAT": {
      "area_ha": 166000.0,
      "production_t": 276000.0,
      "yield_t_per_ha": 1.6627
    },
    "RICE": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "MUR": {
    "WHEAT": {
      "area_ha": 3000.0,
      "production_t": 3000.0,
      "yield_t_per_ha": 1.0
    },
    "RICE": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "ISL": {
    "WHEAT": {
      "area_ha": 19000.0,
      "production_t": 32000.0,
      "yield_t_per_ha": 1.6842
    },
    "RICE": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "PB-JHL": {
    "WHEAT": {
      "area_ha": 84000.0,
      "production_t": 174000.0,
      "yield_t_per_ha": 2.0714
    },
    "RICE": {
      "area_ha": 2430.0,
      "production_t": 4030.0,
      "yield_t_per_ha": 1.6584
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "PB-CKW": {
    "WHEAT": {
      "area_ha": 103000.0,
      "production_t": 168000.0,
      "yield_t_per_ha": 1.6311
    },
    "RICE": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "TAL": {
    "WHEAT": {
      "area_ha": 54000.0,
      "production_t": 78000.0,
      "yield_t_per_ha": 1.4444
    },
    "RICE": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "PB-SGD": {
    "WHEAT": {
      "area_ha": 212000.0,
      "production_t": 669000.0,
      "yield_t_per_ha": 3.1557
    },
    "RICE": {
      "area_ha": 61100.0,
      "production_t": 113540.0,
      "yield_t_per_ha": 1.8583
    },
    "COTTON": {
      "area_ha": 3240.0,
      "production_t": 1269.9,
      "yield_t_per_ha": 0.3919
    }
  },
  "PB-KHB": {
    "WHEAT": {
      "area_ha": 110000.0,
      "production_t": 249000.0,
      "yield_t_per_ha": 2.2636
    },
    "RICE": {
      "area_ha": 16990.0,
      "production_t": 29760.0,
      "yield_t_per_ha": 1.7516
    },
    "COTTON": {
      "area_ha": 810.0,
      "production_t": 421.6,
      "yield_t_per_ha": 0.5205
    }
  },
  "PB-MNW": {
    "WHEAT": {
      "area_ha": 186000.0,
      "production_t": 568000.0,
      "yield_t_per_ha": 3.0538
    },
    "RICE": {
      "area_ha": 3240.0,
      "production_t": 6200.0,
      "yield_t_per_ha": 1.9136
    },
    "COTTON": {
      "area_ha": 41280.0,
      "production_t": 21848.4,
      "yield_t_per_ha": 0.5293
    }
  },
  "PB-BHK": {
    "WHEAT": {
      "area_ha": 177000.0,
      "production_t": 512000.0,
      "yield_t_per_ha": 2.8927
    },
    "RICE": {
      "area_ha": 3650.0,
      "production_t": 8700.0,
      "yield_t_per_ha": 2.3836
    },
    "COTTON": {
      "area_ha": 13350.0,
      "production_t": 6592.6,
      "yield_t_per_ha": 0.4938
    }
  },
  "PB-TTS": {
    "WHEAT": {
      "area_ha": 130000.0,
      "production_t": 506000.0,
      "yield_t_per_ha": 3.8923
    },
    "RICE": {
      "area_ha": 49780.0,
      "production_t": 119530.0,
      "yield_t_per_ha": 2.4012
    },
    "COTTON": {
      "area_ha": 13760.0,
      "production_t": 6203.3,
      "yield_t_per_ha": 0.4508
    }
  },
  "PB-CHT": {
    "WHEAT": {
      "area_ha": 86000.0,
      "production_t": 334000.0,
      "yield_t_per_ha": 3.8837
    },
    "RICE": {
      "area_ha": 48560.0,
      "production_t": 117910.0,
      "yield_t_per_ha": 2.4281
    },
    "COTTON": {
      "area_ha": 400.0,
      "production_t": 187.0,
      "yield_t_per_ha": 0.4675
    }
  },
  "PB-GJT": {
    "WHEAT": {
      "area_ha": 155000.0,
      "production_t": 389000.0,
      "yield_t_per_ha": 2.5097
    },
    "RICE": {
      "area_ha": 35610.0,
      "production_t": 66180.0,
      "yield_t_per_ha": 1.8585
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "PB-MBD": {
    "WHEAT": {
      "area_ha": 135000.0,
      "production_t": 463000.0,
      "yield_t_per_ha": 3.4296
    },
    "RICE": {
      "area_ha": 101170.0,
      "production_t": 203530.0,
      "yield_t_per_ha": 2.0118
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "PB-HFZ": {
    "WHEAT": {
      "area_ha": 155000.0,
      "production_t": 537000.0,
      "yield_t_per_ha": 3.4645
    },
    "RICE": {
      "area_ha": 157830.0,
      "production_t": 293080.0,
      "yield_t_per_ha": 1.8569
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "WAZ": {
    "WHEAT": {
      "area_ha": 73000.0,
      "production_t": 228000.0,
      "yield_t_per_ha": 3.1233
    },
    "RICE": {
      "area_ha": 77700.0,
      "production_t": 157730.0,
      "yield_t_per_ha": 2.03
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "PB-GRW": {
    "WHEAT": {
      "area_ha": 159000.0,
      "production_t": 564000.0,
      "yield_t_per_ha": 3.5472
    },
    "RICE": {
      "area_ha": 172390.0,
      "production_t": 363730.0,
      "yield_t_per_ha": 2.1099
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "PB-SKT": {
    "WHEAT": {
      "area_ha": 192000.0,
      "production_t": 578000.0,
      "yield_t_per_ha": 3.0104
    },
    "RICE": {
      "area_ha": 197480.0,
      "production_t": 347960.0,
      "yield_t_per_ha": 1.762
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "PB-NRW": {
    "WHEAT": {
      "area_ha": 122000.0,
      "production_t": 354000.0,
      "yield_t_per_ha": 2.9016
    },
    "RICE": {
      "area_ha": 83370.0,
      "production_t": 163170.0,
      "yield_t_per_ha": 1.9572
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "PB-SHK": {
    "WHEAT": {
      "area_ha": 227000.0,
      "production_t": 797000.0,
      "yield_t_per_ha": 3.511
    },
    "RICE": {
      "area_ha": 237550.0,
      "production_t": 502700.0,
      "yield_t_per_ha": 2.1162
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "PB-NNK": {
    "WHEAT": {
      "area_ha": 137000.0,
      "production_t": 543000.0,
      "yield_t_per_ha": 3.9635
    },
    "RICE": {
      "area_ha": 115330.0,
      "production_t": 265480.0,
      "yield_t_per_ha": 2.3019
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "PB-LHE": {
    "WHEAT": {
      "area_ha": 47000.0,
      "production_t": 183000.0,
      "yield_t_per_ha": 3.8936
    },
    "RICE": {
      "area_ha": 28730.0,
      "production_t": 60710.0,
      "yield_t_per_ha": 2.1131
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "PB-KSR": {
    "WHEAT": {
      "area_ha": 129000.0,
      "production_t": 498000.0,
      "yield_t_per_ha": 3.8605
    },
    "RICE": {
      "area_ha": 113720.0,
      "production_t": 327830.0,
      "yield_t_per_ha": 2.8828
    },
    "COTTON": {
      "area_ha": 1210.0,
      "production_t": 406.3,
      "yield_t_per_ha": 0.3358
    }
  },
  "PB-OKR": {
    "WHEAT": {
      "area_ha": 127000.0,
      "production_t": 536000.0,
      "yield_t_per_ha": 4.2205
    },
    "RICE": {
      "area_ha": 168750.0,
      "production_t": 431240.0,
      "yield_t_per_ha": 2.5555
    },
    "COTTON": {
      "area_ha": 3240.0,
      "production_t": 2500.7,
      "yield_t_per_ha": 0.7718
    }
  },
  "PB-SHW": {
    "WHEAT": {
      "area_ha": 119000.0,
      "production_t": 456000.0,
      "yield_t_per_ha": 3.8319
    },
    "RICE": {
      "area_ha": 61510.0,
      "production_t": 164490.0,
      "yield_t_per_ha": 2.6742
    },
    "COTTON": {
      "area_ha": 20640.0,
      "production_t": 16357.4,
      "yield_t_per_ha": 0.7925
    }
  },
  "PB-PKP": {
    "WHEAT": {
      "area_ha": 87000.0,
      "production_t": 363000.0,
      "yield_t_per_ha": 4.1724
    },
    "RICE": {
      "area_ha": 123020.0,
      "production_t": 325720.0,
      "yield_t_per_ha": 2.6477
    },
    "COTTON": {
      "area_ha": 4450.0,
      "production_t": 2847.5,
      "yield_t_per_ha": 0.6399
    }
  },
  "PB-MLN": {
    "WHEAT": {
      "area_ha": 177000.0,
      "production_t": 682000.0,
      "yield_t_per_ha": 3.8531
    },
    "RICE": {
      "area_ha": 40870.0,
      "production_t": 83180.0,
      "yield_t_per_ha": 2.0352
    },
    "COTTON": {
      "area_ha": 81340.0,
      "production_t": 47610.2,
      "yield_t_per_ha": 0.5853
    }
  },
  "PB-LDN": {
    "WHEAT": {
      "area_ha": 150000.0,
      "production_t": 594000.0,
      "yield_t_per_ha": 3.96
    },
    "RICE": {
      "area_ha": 21440.0,
      "production_t": 44690.0,
      "yield_t_per_ha": 2.0844
    },
    "COTTON": {
      "area_ha": 88220.0,
      "production_t": 49289.8,
      "yield_t_per_ha": 0.5587
    }
  },
  "PB-KHW": {
    "WHEAT": {
      "area_ha": 200000.0,
      "production_t": 804000.0,
      "yield_t_per_ha": 4.02
    },
    "RICE": {
      "area_ha": 76000.0,
      "production_t": 176310.0,
      "yield_t_per_ha": 2.3199
    },
    "COTTON": {
      "area_ha": 70410.0,
      "production_t": 45257.4,
      "yield_t_per_ha": 0.6428
    }
  },
  "PB-VHR": {
    "WHEAT": {
      "area_ha": 180000.0,
      "production_t": 707000.0,
      "yield_t_per_ha": 3.9278
    },
    "RICE": {
      "area_ha": 64340.0,
      "production_t": 162890.0,
      "yield_t_per_ha": 2.5317
    },
    "COTTON": {
      "area_ha": 50180.0,
      "production_t": 31795.1,
      "yield_t_per_ha": 0.6336
    }
  },
  "PB-MZG": {
    "WHEAT": {
      "area_ha": 146000.0,
      "production_t": 522000.0,
      "yield_t_per_ha": 3.5753
    },
    "RICE": {
      "area_ha": 32780.0,
      "production_t": 63610.0,
      "yield_t_per_ha": 1.9405
    },
    "COTTON": {
      "area_ha": 42090.0,
      "production_t": 13642.5,
      "yield_t_per_ha": 0.3241
    }
  },
  "KOT": {
    "WHEAT": {
      "area_ha": 95000.0,
      "production_t": 317000.0,
      "yield_t_per_ha": 3.3368
    },
    "RICE": {
      "area_ha": 7290.0,
      "production_t": 15840.0,
      "yield_t_per_ha": 2.1728
    },
    "COTTON": {
      "area_ha": 8900.0,
      "production_t": 3014.1,
      "yield_t_per_ha": 0.3387
    }
  },
  "PB-LYH": {
    "WHEAT": {
      "area_ha": 260000.0,
      "production_t": 804000.0,
      "yield_t_per_ha": 3.0923
    },
    "RICE": {
      "area_ha": 1620.0,
      "production_t": 3440.0,
      "yield_t_per_ha": 2.1235
    },
    "COTTON": {
      "area_ha": 34400.0,
      "production_t": 7417.1,
      "yield_t_per_ha": 0.2156
    }
  },
  "PB-DGK": {
    "WHEAT": {
      "area_ha": 129000.0,
      "production_t": 504000.0,
      "yield_t_per_ha": 3.907
    },
    "RICE": {
      "area_ha": 76880.0,
      "production_t": 236100.0,
      "yield_t_per_ha": 3.071
    },
    "COTTON": {
      "area_ha": 11330.0,
      "production_t": 5701.8,
      "yield_t_per_ha": 0.5032
    }
  },
  "TAU": {
    "WHEAT": {
      "area_ha": 100000.0,
      "production_t": 350000.0,
      "yield_t_per_ha": 3.5
    },
    "RICE": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    },
    "COTTON": {
      "area_ha": 11740.0,
      "production_t": 4819.5,
      "yield_t_per_ha": 0.4105
    }
  },
  "PB-RJN": {
    "WHEAT": {
      "area_ha": 178000.0,
      "production_t": 627000.0,
      "yield_t_per_ha": 3.5225
    },
    "RICE": {
      "area_ha": 38450.0,
      "production_t": 102660.0,
      "yield_t_per_ha": 2.67
    },
    "COTTON": {
      "area_ha": 74460.0,
      "production_t": 29272.3,
      "yield_t_per_ha": 0.3931
    }
  },
  "SD-KHP": {
    "WHEAT": {
      "area_ha": 111970.0,
      "production_t": 333230.0,
      "yield_t_per_ha": 2.9761
    },
    "RICE": {
      "area_ha": 33080.0,
      "production_t": 112400.0,
      "yield_t_per_ha": 3.3978
    },
    "COTTON": {
      "area_ha": 80670.0,
      "production_t": 55794.0,
      "yield_t_per_ha": 0.6916
    }
  },
  "SD-GTK": {
    "WHEAT": {
      "area_ha": 108790.0,
      "production_t": 301100.0,
      "yield_t_per_ha": 2.7677
    },
    "RICE": {
      "area_ha": 51150.0,
      "production_t": 166490.0,
      "yield_t_per_ha": 3.2549
    },
    "COTTON": {
      "area_ha": 82560.0,
      "production_t": 64822.7,
      "yield_t_per_ha": 0.7852
    }
  },
  "SD-SKR": {
    "WHEAT": {
      "area_ha": 52570.0,
      "production_t": 145480.0,
      "yield_t_per_ha": 2.7674
    },
    "RICE": {
      "area_ha": 1580.0,
      "production_t": 4550.0,
      "yield_t_per_ha": 2.8797
    },
    "COTTON": {
      "area_ha": 24380.0,
      "production_t": 20194.3,
      "yield_t_per_ha": 0.8283
    }
  },
  "SD-NSF": {
    "WHEAT": {
      "area_ha": 116150.0,
      "production_t": 335460.0,
      "yield_t_per_ha": 2.8882
    },
    "RICE": {
      "area_ha": 30210.0,
      "production_t": 97190.0,
      "yield_t_per_ha": 3.2171
    },
    "COTTON": {
      "area_ha": 32440.0,
      "production_t": 26967.1,
      "yield_t_per_ha": 0.8313
    }
  },
  "SD-SBZ": {
    "WHEAT": {
      "area_ha": 89870.0,
      "production_t": 260620.0,
      "yield_t_per_ha": 2.9
    },
    "RICE": {
      "area_ha": 3900.0,
      "production_t": 10710.0,
      "yield_t_per_ha": 2.7462
    },
    "COTTON": {
      "area_ha": 294000.0,
      "production_t": 26180.0,
      "yield_t_per_ha": 0.089
    }
  },
  "SD-JCB": {
    "WHEAT": {
      "area_ha": 34420.0,
      "production_t": 85050.0,
      "yield_t_per_ha": 2.4709
    },
    "RICE": {
      "area_ha": 115240.0,
      "production_t": 344800.0,
      "yield_t_per_ha": 2.992
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "SD-KSH": {
    "WHEAT": {
      "area_ha": 53750.0,
      "production_t": 138130.0,
      "yield_t_per_ha": 2.5699
    },
    "RICE": {
      "area_ha": 84460.0,
      "production_t": 252070.0,
      "yield_t_per_ha": 2.9845
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "SD-SHK": {
    "WHEAT": {
      "area_ha": 45550.0,
      "production_t": 135070.0,
      "yield_t_per_ha": 2.9653
    },
    "RICE": {
      "area_ha": 117500.0,
      "production_t": 371670.0,
      "yield_t_per_ha": 3.1631
    },
    "COTTON": {
      "area_ha": 140.0,
      "production_t": 113.9,
      "yield_t_per_ha": 0.8136
    }
  },
  "SD-LRK": {
    "WHEAT": {
      "area_ha": 56170.0,
      "production_t": 170230.0,
      "yield_t_per_ha": 3.0306
    },
    "RICE": {
      "area_ha": 109640.0,
      "production_t": 357410.0,
      "yield_t_per_ha": 3.2599
    },
    "COTTON": {
      "area_ha": 1750.0,
      "production_t": 1395.7,
      "yield_t_per_ha": 0.7975
    }
  },
  "SD-KMB": {
    "WHEAT": {
      "area_ha": 73120.0,
      "production_t": 198760.0,
      "yield_t_per_ha": 2.7183
    },
    "RICE": {
      "area_ha": 91500.0,
      "production_t": 321880.0,
      "yield_t_per_ha": 3.5178
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "SD-SGR": {
    "WHEAT": {
      "area_ha": 122670.0,
      "production_t": 339500.0,
      "yield_t_per_ha": 2.7676
    },
    "RICE": {
      "area_ha": 47310.0,
      "production_t": 141390.0,
      "yield_t_per_ha": 2.9886
    },
    "COTTON": {
      "area_ha": 121260.0,
      "production_t": 117594.1,
      "yield_t_per_ha": 0.9698
    }
  },
  "SD-TPK": {
    "WHEAT": {
      "area_ha": 4460.0,
      "production_t": 12330.0,
      "yield_t_per_ha": 2.7646
    },
    "RICE": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    },
    "COTTON": {
      "area_ha": 1240.0,
      "production_t": 1128.8,
      "yield_t_per_ha": 0.9103
    }
  },
  "SD-MPK": {
    "WHEAT": {
      "area_ha": 67890.0,
      "production_t": 187900.0,
      "yield_t_per_ha": 2.7677
    },
    "RICE": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    },
    "COTTON": {
      "area_ha": 28400.0,
      "production_t": 24736.7,
      "yield_t_per_ha": 0.871
    }
  },
  "SD-UMK": {
    "WHEAT": {
      "area_ha": 42670.0,
      "production_t": 122310.0,
      "yield_t_per_ha": 2.8664
    },
    "RICE": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    },
    "COTTON": {
      "area_ha": 26700.0,
      "production_t": 23167.6,
      "yield_t_per_ha": 0.8677
    }
  },
  "SD-DDU": {
    "WHEAT": {
      "area_ha": 79000.0,
      "production_t": 229900.0,
      "yield_t_per_ha": 2.9101
    },
    "RICE": {
      "area_ha": 120.0,
      "production_t": 130.0,
      "yield_t_per_ha": 1.0833
    },
    "COTTON": {
      "area_ha": 10510.0,
      "production_t": 7837.0,
      "yield_t_per_ha": 0.7457
    }
  },
  "SD-JAM": {
    "WHEAT": {
      "area_ha": 37970.0,
      "production_t": 110900.0,
      "yield_t_per_ha": 2.9207
    },
    "RICE": {
      "area_ha": 500.0,
      "production_t": 1450.0,
      "yield_t_per_ha": 2.9
    },
    "COTTON": {
      "area_ha": 15530.0,
      "production_t": 11777.6,
      "yield_t_per_ha": 0.7584
    }
  },
  "SD-HYD": {
    "WHEAT": {
      "area_ha": 12870.0,
      "production_t": 38150.0,
      "yield_t_per_ha": 2.9643
    },
    "RICE": {
      "area_ha": 920.0,
      "production_t": 3170.0,
      "yield_t_per_ha": 3.4457
    },
    "COTTON": {
      "area_ha": 4130.0,
      "production_t": 3519.0,
      "yield_t_per_ha": 0.8521
    }
  },
  "SD-MTR": {
    "WHEAT": {
      "area_ha": 43450.0,
      "production_t": 125490.0,
      "yield_t_per_ha": 2.8881
    },
    "RICE": {
      "area_ha": 2870.0,
      "production_t": 8450.0,
      "yield_t_per_ha": 2.9443
    },
    "COTTON": {
      "area_ha": 40580.0,
      "production_t": 32823.6,
      "yield_t_per_ha": 0.8089
    }
  },
  "SD-TDA": {
    "WHEAT": {
      "area_ha": 28460.0,
      "production_t": 81890.0,
      "yield_t_per_ha": 2.8774
    },
    "RICE": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    },
    "COTTON": {
      "area_ha": 20480.0,
      "production_t": 16719.5,
      "yield_t_per_ha": 0.8164
    }
  },
  "SD-TMK": {
    "WHEAT": {
      "area_ha": 18310.0,
      "production_t": 52880.0,
      "yield_t_per_ha": 2.888
    },
    "RICE": {
      "area_ha": 13400.0,
      "production_t": 36750.0,
      "yield_t_per_ha": 2.7425
    },
    "COTTON": {
      "area_ha": 3500.0,
      "production_t": 2781.2,
      "yield_t_per_ha": 0.7946
    }
  },
  "SD-BDN": {
    "WHEAT": {
      "area_ha": 27260.0,
      "production_t": 78130.0,
      "yield_t_per_ha": 2.8661
    },
    "RICE": {
      "area_ha": 125000.0,
      "production_t": 364550.0,
      "yield_t_per_ha": 2.9164
    },
    "COTTON": {
      "area_ha": 17380.0,
      "production_t": 13674.8,
      "yield_t_per_ha": 0.7868
    }
  },
  "SD-THT": {
    "WHEAT": {
      "area_ha": 20220.0,
      "production_t": 55960.0,
      "yield_t_per_ha": 2.7676
    },
    "RICE": {
      "area_ha": 83590.0,
      "production_t": 243420.0,
      "yield_t_per_ha": 2.9121
    },
    "COTTON": {
      "area_ha": 5200.0,
      "production_t": 3488.4,
      "yield_t_per_ha": 0.6708
    }
  },
  "SD-KHI": {
    "WHEAT": {
      "area_ha": 1410.0,
      "production_t": 4040.0,
      "yield_t_per_ha": 2.8652
    },
    "RICE": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    },
    "COTTON": {
      "area_ha": 350.0,
      "production_t": 294.1,
      "yield_t_per_ha": 0.8403
    }
  },
  "KP-BNU": {
    "WHEAT": {
      "area_ha": 5240.0,
      "production_t": 9830.0,
      "yield_t_per_ha": 1.876
    },
    "RICE": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "LAK": {
    "WHEAT": {
      "area_ha": 18580.0,
      "production_t": 22080.0,
      "yield_t_per_ha": 1.1884
    },
    "RICE": {
      "area_ha": 220.0,
      "production_t": 330.0,
      "yield_t_per_ha": 1.5
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "KP-DIK": {
    "WHEAT": {
      "area_ha": 5610.0,
      "production_t": 8250.0,
      "yield_t_per_ha": 1.4706
    },
    "RICE": {
      "area_ha": 100.0,
      "production_t": 170.0,
      "yield_t_per_ha": 1.7
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "TAN": {
    "WHEAT": {
      "area_ha": 8980.0,
      "production_t": 18920.0,
      "yield_t_per_ha": 2.1069
    },
    "RICE": {
      "area_ha": 1470.0,
      "production_t": 2500.0,
      "yield_t_per_ha": 1.7007
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "KP-ABT": {
    "WHEAT": {
      "area_ha": 14660.0,
      "production_t": 22610.0,
      "yield_t_per_ha": 1.5423
    },
    "RICE": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "BAT": {
    "WHEAT": {
      "area_ha": 7850.0,
      "production_t": 12220.0,
      "yield_t_per_ha": 1.5567
    },
    "RICE": {
      "area_ha": 1530.0,
      "production_t": 3340.0,
      "yield_t_per_ha": 2.183
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "KP-HRP": {
    "WHEAT": {
      "area_ha": 35280.0,
      "production_t": 51690.0,
      "yield_t_per_ha": 1.4651
    },
    "RICE": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "KOH": {
    "WHEAT": {
      "area_ha": 9690.0,
      "production_t": 25230.0,
      "yield_t_per_ha": 2.6037
    },
    "RICE": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    },
    "COTTON": {
      "area_ha": 8140.0,
      "production_t": 3859.0,
      "yield_t_per_ha": 0.4741
    }
  },
  "TOR": {
    "WHEAT": {
      "area_ha": 6190.0,
      "production_t": 8890.0,
      "yield_t_per_ha": 1.4362
    }
  },
  "KP-MNS": {
    "WHEAT": {
      "area_ha": 34600.0,
      "production_t": 56760.0,
      "yield_t_per_ha": 1.6405
    },
    "RICE": {
      "area_ha": 1350.0,
      "production_t": 3540.0,
      "yield_t_per_ha": 2.6222
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "KP-KHT": {
    "WHEAT": {
      "area_ha": 5240.0,
      "production_t": 10210.0,
      "yield_t_per_ha": 1.9485
    },
    "RICE": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "KAR": {
    "WHEAT": {
      "area_ha": 5550.0,
      "production_t": 3820.0,
      "yield_t_per_ha": 0.6883
    },
    "RICE": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "HAN": {
    "WHEAT": {
      "area_ha": 7430.0,
      "production_t": 10530.0,
      "yield_t_per_ha": 1.4172
    },
    "RICE": {
      "area_ha": 10.0,
      "production_t": 20.0,
      "yield_t_per_ha": 2.0
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "KP-MRD": {
    "WHEAT": {
      "area_ha": 42070.0,
      "production_t": 113290.0,
      "yield_t_per_ha": 2.6929
    },
    "RICE": {
      "area_ha": 2970.0,
      "production_t": 6000.0,
      "yield_t_per_ha": 2.0202
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "KP-SWB": {
    "WHEAT": {
      "area_ha": 36790.0,
      "production_t": 89120.0,
      "yield_t_per_ha": 2.4224
    },
    "RICE": {
      "area_ha": 500.0,
      "production_t": 900.0,
      "yield_t_per_ha": 1.8
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "BUN": {
    "WHEAT": {
      "area_ha": 47050.0,
      "production_t": 61650.0,
      "yield_t_per_ha": 1.3103
    },
    "RICE": {
      "area_ha": 120.0,
      "production_t": 270.0,
      "yield_t_per_ha": 2.25
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "CHI": {
    "WHEAT": {
      "area_ha": 8260.0,
      "production_t": 15880.0,
      "yield_t_per_ha": 1.9225
    },
    "RICE": {
      "area_ha": 1820.0,
      "production_t": 5090.0,
      "yield_t_per_ha": 2.7967
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "MAL": {
    "WHEAT": {
      "area_ha": 22350.0,
      "production_t": 54810.0,
      "yield_t_per_ha": 2.4523
    },
    "RICE": {
      "area_ha": 4720.0,
      "production_t": 14470.0,
      "yield_t_per_ha": 3.0657
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "DIR": {
    "WHEAT": {
      "area_ha": 26680.0,
      "production_t": 50460.0,
      "yield_t_per_ha": 1.8913
    },
    "RICE": {
      "area_ha": 7030.0,
      "production_t": 17590.0,
      "yield_t_per_ha": 2.5021
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "SHA": {
    "WHEAT": {
      "area_ha": 24770.0,
      "production_t": 31570.0,
      "yield_t_per_ha": 1.2745
    },
    "RICE": {
      "area_ha": 1390.0,
      "production_t": 3870.0,
      "yield_t_per_ha": 2.7842
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "KP-SWT": {
    "WHEAT": {
      "area_ha": 57430.0,
      "production_t": 106810.0,
      "yield_t_per_ha": 1.8598
    },
    "RICE": {
      "area_ha": 4070.0,
      "production_t": 13840.0,
      "yield_t_per_ha": 3.4005
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "KP-PSH": {
    "WHEAT": {
      "area_ha": 32160.0,
      "production_t": 86930.0,
      "yield_t_per_ha": 2.703
    },
    "RICE": {
      "area_ha": 20.0,
      "production_t": 70.0,
      "yield_t_per_ha": 3.5
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "KP-CHR": {
    "WHEAT": {
      "area_ha": 31580.0,
      "production_t": 90700.0,
      "yield_t_per_ha": 2.8721
    },
    "RICE": {
      "area_ha": 70.0,
      "production_t": 160.0,
      "yield_t_per_ha": 2.2857
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "KP-NSH": {
    "WHEAT": {
      "area_ha": 22240.0,
      "production_t": 56430.0,
      "yield_t_per_ha": 2.5373
    },
    "RICE": {
      "area_ha": 30.0,
      "production_t": 60.0,
      "yield_t_per_ha": 2.0
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "BAJ": {
    "WHEAT": {
      "area_ha": 40330.0,
      "production_t": 70980.0,
      "yield_t_per_ha": 1.76
    },
    "RICE": {
      "area_ha": 4790.0,
      "production_t": 7980.0,
      "yield_t_per_ha": 1.666
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "KUR": {
    "WHEAT": {
      "area_ha": 27460.0,
      "production_t": 56090.0,
      "yield_t_per_ha": 2.0426
    },
    "RICE": {
      "area_ha": 6020.0,
      "production_t": 17380.0,
      "yield_t_per_ha": 2.887
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "MUH": {
    "WHEAT": {
      "area_ha": 8450.0,
      "production_t": 13290.0,
      "yield_t_per_ha": 1.5728
    },
    "RICE": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "N. ": {
    "WHEAT": {
      "area_ha": 5920.0,
      "production_t": 12740.0,
      "yield_t_per_ha": 2.152
    },
    "RICE": {
      "area_ha": 330.0,
      "production_t": 650.0,
      "yield_t_per_ha": 1.9697
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "S. ": {
    "WHEAT": {
      "area_ha": 4870.0,
      "production_t": 8490.0,
      "yield_t_per_ha": 1.7433
    },
    "RICE": {
      "area_ha": 470.0,
      "production_t": 870.0,
      "yield_t_per_ha": 1.8511
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "ORI": {
    "WHEAT": {
      "area_ha": 9980.0,
      "production_t": 15220.0,
      "yield_t_per_ha": 1.5251
    },
    "RICE": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "SD ": {
    "WHEAT": {
      "area_ha": 1890.0,
      "production_t": 3210.0,
      "yield_t_per_ha": 1.6984
    },
    "RICE": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "BL-QTA": {
    "WHEAT": {
      "area_ha": 2080.0,
      "production_t": 5340.0,
      "yield_t_per_ha": 2.5673
    },
    "RICE": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "PIS": {
    "WHEAT": {
      "area_ha": 5260.0,
      "production_t": 12800.0,
      "yield_t_per_ha": 2.4335
    },
    "RICE": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "K. ": {
    "WHEAT": {
      "area_ha": 1610.0,
      "production_t": 3890.0,
      "yield_t_per_ha": 2.4161
    },
    "RICE": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "CHA": {
    "WHEAT": {
      "area_ha": 9250.0,
      "production_t": 21900.0,
      "yield_t_per_ha": 2.3676
    },
    "RICE": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    },
    "COTTON": {
      "area_ha": 270.0,
      "production_t": 125.8,
      "yield_t_per_ha": 0.4659
    }
  },
  "NUS": {
    "WHEAT": {
      "area_ha": 8290.0,
      "production_t": 21050.0,
      "yield_t_per_ha": 2.5392
    },
    "RICE": {
      "area_ha": 30.0,
      "production_t": 40.0,
      "yield_t_per_ha": 1.3333
    },
    "COTTON": {
      "area_ha": 2540.0,
      "production_t": 1208.7,
      "yield_t_per_ha": 0.4759
    }
  },
  "BL-LRL": {
    "WHEAT": {
      "area_ha": 10240.0,
      "production_t": 30790.0,
      "yield_t_per_ha": 3.0068
    },
    "RICE": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    },
    "COTTON": {
      "area_ha": 410.0,
      "production_t": 188.7,
      "yield_t_per_ha": 0.4602
    }
  },
  "MUS": {
    "WHEAT": {
      "area_ha": 5420.0,
      "production_t": 9630.0,
      "yield_t_per_ha": 1.7768
    },
    "RICE": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    },
    "COTTON": {
      "area_ha": 20.0,
      "production_t": 6.8,
      "yield_t_per_ha": 0.34
    }
  },
  "BAR": {
    "WHEAT": {
      "area_ha": 16590.0,
      "production_t": 42890.0,
      "yield_t_per_ha": 2.5853
    },
    "RICE": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    },
    "COTTON": {
      "area_ha": 17130.0,
      "production_t": 7478.3,
      "yield_t_per_ha": 0.4366
    }
  },
  "BL-ZHB": {
    "WHEAT": {
      "area_ha": 6370.0,
      "production_t": 14960.0,
      "yield_t_per_ha": 2.3485
    },
    "RICE": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "SHE": {
    "WHEAT": {
      "area_ha": 1330.0,
      "production_t": 2710.0,
      "yield_t_per_ha": 2.0376
    },
    "RICE": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "KIL": {
    "WHEAT": {
      "area_ha": 8390.0,
      "production_t": 21570.0,
      "yield_t_per_ha": 2.5709
    },
    "RICE": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    },
    "COTTON": {
      "area_ha": 40.0,
      "production_t": 18.7,
      "yield_t_per_ha": 0.4675
    }
  },
  "BL-SBI": {
    "WHEAT": {
      "area_ha": 16040.0,
      "production_t": 40840.0,
      "yield_t_per_ha": 2.5461
    },
    "RICE": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    },
    "COTTON": {
      "area_ha": 11070.0,
      "production_t": 4705.6,
      "yield_t_per_ha": 0.4251
    }
  },
  "HAR": {
    "WHEAT": {
      "area_ha": 2880.0,
      "production_t": 7350.0,
      "yield_t_per_ha": 2.5521
    },
    "RICE": {
      "area_ha": 90.0,
      "production_t": 230.0,
      "yield_t_per_ha": 2.5556
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "ZIA": {
    "WHEAT": {
      "area_ha": 600.0,
      "production_t": 1280.0,
      "yield_t_per_ha": 2.1333
    },
    "RICE": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "DER": {
    "WHEAT": {
      "area_ha": 24640.0,
      "production_t": 49260.0,
      "yield_t_per_ha": 1.9992
    },
    "RICE": {
      "area_ha": 230.0,
      "production_t": 690.0,
      "yield_t_per_ha": 3.0
    },
    "COTTON": {
      "area_ha": 3990.0,
      "production_t": 1683.0,
      "yield_t_per_ha": 0.4218
    }
  },
  "BL-NSB": {
    "WHEAT": {
      "area_ha": 79330.0,
      "production_t": 277560.0,
      "yield_t_per_ha": 3.4988
    },
    "RICE": {
      "area_ha": 62300.0,
      "production_t": 213890.0,
      "yield_t_per_ha": 3.4332
    },
    "COTTON": {
      "area_ha": 3900.0,
      "production_t": 1618.4,
      "yield_t_per_ha": 0.415
    }
  },
  "BL-JFB": {
    "WHEAT": {
      "area_ha": 81800.0,
      "production_t": 269950.0,
      "yield_t_per_ha": 3.3001
    },
    "RICE": {
      "area_ha": 94890.0,
      "production_t": 314210.0,
      "yield_t_per_ha": 3.3113
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "BL-KCH": {
    "WHEAT": {
      "area_ha": 22990.0,
      "production_t": 59240.0,
      "yield_t_per_ha": 2.5768
    },
    "RICE": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    },
    "COTTON": {
      "area_ha": 1810.0,
      "production_t": 827.9,
      "yield_t_per_ha": 0.4574
    }
  },
  "JHA": {
    "WHEAT": {
      "area_ha": 56080.0,
      "production_t": 173120.0,
      "yield_t_per_ha": 3.087
    },
    "RICE": {
      "area_ha": 250.0,
      "production_t": 740.0,
      "yield_t_per_ha": 2.96
    },
    "COTTON": {
      "area_ha": 10.0,
      "production_t": 6.8,
      "yield_t_per_ha": 0.68
    }
  },
  "BL-KLT": {
    "WHEAT": {
      "area_ha": 5450.0,
      "production_t": 17140.0,
      "yield_t_per_ha": 3.145
    },
    "RICE": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    },
    "COTTON": {
      "area_ha": 10.0,
      "production_t": 3.4,
      "yield_t_per_ha": 0.34
    }
  },
  "MAS": {
    "WHEAT": {
      "area_ha": 2050.0,
      "production_t": 3960.0,
      "yield_t_per_ha": 1.9317
    },
    "RICE": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  },
  "BL-KZD": {
    "WHEAT": {
      "area_ha": 58700.0,
      "production_t": 151650.0,
      "yield_t_per_ha": 2.5835
    },
    "RICE": {
      "area_ha": 1000.0,
      "production_t": 3060.0,
      "yield_t_per_ha": 3.06
    },
    "COTTON": {
      "area_ha": 23400.0,
      "production_t": 10873.2,
      "yield_t_per_ha": 0.4647
    }
  },
  "AWA": {
    "WHEAT": {
      "area_ha": 21020.0,
      "production_t": 52820.0,
      "yield_t_per_ha": 2.5128
    },
    "RICE": {
      "area_ha": 280.0,
      "production_t": 650.0,
      "yield_t_per_ha": 2.3214
    },
    "COTTON": {
      "area_ha": 2950.0,
      "production_t": 1414.4,
      "yield_t_per_ha": 0.4795
    }
  },
  "KHA": {
    "WHEAT": {
      "area_ha": 13320.0,
      "production_t": 34850.0,
      "yield_t_per_ha": 2.6164
    },
    "RICE": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    },
    "COTTON": {
      "area_ha": 18540.0,
      "production_t": 7877.8,
      "yield_t_per_ha": 0.4249
    }
  },
  "WAS": {
    "WHEAT": {
      "area_ha": 10060.0,
      "production_t": 20270.0,
      "yield_t_per_ha": 2.0149
    },
    "RICE": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    },
    "COTTON": {
      "area_ha": 1200.0,
      "production_t": 479.4,
      "yield_t_per_ha": 0.3995
    }
  },
  "LAS": {
    "WHEAT": {
      "area_ha": 25280.0,
      "production_t": 67750.0,
      "yield_t_per_ha": 2.68
    },
    "RICE": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    },
    "COTTON": {
      "area_ha": 52040.0,
      "production_t": 25413.3,
      "yield_t_per_ha": 0.4883
    }
  },
  "TUR": {
    "WHEAT": {
      "area_ha": 3690.0,
      "production_t": 10660.0,
      "yield_t_per_ha": 2.8889
    },
    "RICE": {
      "area_ha": 1130.0,
      "production_t": 2610.0,
      "yield_t_per_ha": 2.3097
    },
    "COTTON": {
      "area_ha": 8060.0,
      "production_t": 3437.4,
      "yield_t_per_ha": 0.4265
    }
  },
  "PAN": {
    "WHEAT": {
      "area_ha": 8800.0,
      "production_t": 19300.0,
      "yield_t_per_ha": 2.1932
    },
    "RICE": {
      "area_ha": 20.0,
      "production_t": 60.0,
      "yield_t_per_ha": 3.0
    },
    "COTTON": {
      "area_ha": 1390.0,
      "production_t": 589.9,
      "yield_t_per_ha": 0.4244
    }
  },
  "GWA": {
    "WHEAT": {
      "area_ha": 360.0,
      "production_t": 820.0,
      "yield_t_per_ha": 2.2778
    },
    "RICE": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    },
    "COTTON": {
      "area_ha": 120.0,
      "production_t": 49.3,
      "yield_t_per_ha": 0.4108
    }
  },
  "BOL": {
    "RICE": {
      "area_ha": 1070.0,
      "production_t": 910.0,
      "yield_t_per_ha": 0.8505
    },
    "COTTON": {
      "area_ha": 0.0,
      "production_t": 0.0,
      "yield_t_per_ha": 0.0
    }
  }
};

const CONSUMPTION_RATES_KG = {
    WHEAT:  124,   // kg/person/year (Pakistan Economic Survey)
    RICE:   24,    // kg/person/year
    COTTON: 5,  // kg/person/year
};

const DATA_YEAR = "2024-25";
const CROP_CODES = ["WHEAT", "RICE", "COTTON"];

async function seedRealProductionData() {
    console.log("🌾 Seeding REAL district production data from MNFSR...");

    const cropTypes = await CropType.find({});
    const cropMap = {};
    cropTypes.forEach(c => cropMap[c.code] = c);

    const districts = await District.find({}).populate("province");
    let inserted = 0;
    let skipped = 0;

    for (const district of districts) {
        const districtData = REAL_DISTRICT_DATA[district.code];

        for (const cropCode of CROP_CODES) {
            const cropType = cropMap[cropCode];
            if (!cropType) continue;

            let productionRecord;

            if (districtData && districtData[cropCode]) {
                // ✅ USE REAL DATA from MNFSR
                const real = districtData[cropCode];
                productionRecord = {
                    year:          DATA_YEAR,
                    cropYear:      { startYear: parseInt(DATA_YEAR), endYear: parseInt(DATA_YEAR) + 1 },
                    level:         "district",
                    province:      district.province._id,
                    provinceCode:  district.provinceCode,
                    district:      district._id,
                    districtCode:  district.code,
                    cropType:      cropType._id,
                    cropCode:      cropCode,
                    cropName:      cropType.name,
                    areaCultivated: { value: real.area_ha,        unit: "hectares" },
                    production:     { value: real.production_t,    unit: "tonnes" },
                    yield:          { value: real.yield_t_per_ha,  unit: "tonnes_per_hectare" },
                    dataSource:    "MNFSR_Official",      // ← REAL, not "Estimated"
                    reliability:   "high",                // ← high, not "medium"
                    notes:         `Source: MNFSR Crops Area and Production District Wise ${DATA_YEAR}`,
                };
                inserted++;
            } else {
                // ⚠️ District not found in MNFSR data — skip rather than guess
                console.log(`   ⚠️  No MNFSR data for ${district.name} (${district.code}) - ${cropCode}, skipping`);
                skipped++;
                continue;
            }

            // Upsert — safe to re-run
            await ProductionData.findOneAndUpdate(
                { year: DATA_YEAR, districtCode: district.code, cropCode },
                productionRecord,
                { upsert: true, new: true }
            );

            // Calculate and save surplus/deficit
            const population = district.population || 0;
            const consumptionRate = CONSUMPTION_RATES_KG[cropCode];
            const consumption = (population * consumptionRate) / 1000;
            const production = productionRecord.production.value;
            const balance = production - consumption;
            const percentage = consumption > 0 ? (balance / consumption) * 100 : 0;
            const selfSufficiency = consumption > 0 ? (production / consumption) * 100 : 0;

            let status, severity;
            if (balance > consumption * 0.05)       status = "surplus";
            else if (balance < -consumption * 0.05) status = "deficit";
            else                                     status = "balanced";

            if (status === "deficit") {
                const absPct = Math.abs(percentage);
                if (absPct > 30)      severity = "critical";
                else if (absPct > 15) severity = "moderate";
                else                  severity = "mild";
            } else {
                severity = "none";
            }

            await SurplusDeficit.findOneAndUpdate(
                { year: DATA_YEAR, districtCode: district.code, cropCode },
                {
                    year:                    DATA_YEAR,
                    level:                   "district",
                    province:                district.province._id,
                    provinceCode:            district.provinceCode,
                    district:                district._id,
                    districtCode:            district.code,
                    cropType:                cropType._id,
                    cropCode,
                    production,
                    consumption:             Math.round(consumption),
                    balance:                 Math.round(balance),
                    status,
                    surplusDeficitPercentage: Math.round(percentage * 100) / 100,
                    selfSufficiencyRatio:    Math.round(selfSufficiency * 100) / 100,
                    severity,
                    requiresIntervention:    ["critical", "moderate"].includes(severity),
                    calculatedAt:            new Date(),
                    dataSource:              "MNFSR_Official",
                },
                { upsert: true, new: true }
            );
        }
    }

    console.log(`✅ Done: ${inserted} real records inserted, ${skipped} districts skipped (not in MNFSR data)`);
}

mongoose.connect(process.env.MONGODB_URI || "mongodb://localhost:27017/cropconnect")
    .then(async () => {
        await seedRealProductionData();
        mongoose.disconnect();
    })
    .catch(err => {
        console.error("DB connection failed:", err);
        process.exit(1);
    });
